### ISSUE TITLE
Exception HOTLINE SDK INVALID THEME FILE

### ISSUE THREAD

**Issue by metpb** [freshdesk/hotline-ios#10]
`Terminating app due to uncaught exception 'HOTLINE_SDK_INVALID_THEME_FILE', reason: 'You are attempting to set a theme file "HLTheme" that is not linked with the project through HLResourcesBundle'`

I followed this integration guide:
https://support.hotline.io/support/solutions/articles/221186-hotline-ios-sdk-integration-for-swift-apps

Can't really figure out the issue

Edit: If it helps, there's no file named "HLTheme" in my HLResourcesBundle. It only contains a CSS file named "normalize"

**Comment by arvpo** [comment]
Hi Prasanna,

Looks like HLTheme.plist (our default theme plist file) has not integrated with your XCode project. Would like to know how you integrated the SDK to the project to figure out the issue..  Are you using cocoapods or imported our SDK directly to the project ?

**Comment by metpb** [comment]
Hi, I'm using Cocoapods

Edit: My project written in Swift and I followed [this](https://support.hotline.io/support/solutions/articles/221186-hotline-ios-sdk-integration-for-swift-apps) integration guideline

**Comment by arjunpaliath** [comment]
Hi Prasanna, 

Can we have a remote session? Like TeamViewer or Goto Meeting? 
Would need more information to troubleshoot this issue.
Please send an email to support@hotline.io so that we can set up a call.

**Comment by hrishikesh-p** [comment]
@metpb Hi Prasanna , 

Is this issue resolved ? Can you please with the latest version of the SDK ( v1.2) . If it is not , kindly drop us  an email at support@hotline.io . 

Closing this issue here.

**Comment by metpb** [comment]
Hey @hrishikesh-p 

The issue was fixed. 

This was a weird bug, in that, source-control/git wasn't adding the `HLTheme.plist` & `Info.plist` file under `HLResources.bundle` even after `git add . `

`git add . -f` fixed the issue, but I am still confused on why `git` wasn't able to detect those files.

**Comment by hrishikesh-p** [comment]
@metpb  If you are making changes to the Theme file . I would recommend creating a copy of the theme file in your project. That way a pod update or install would not replace the file. You can also rename the file if need be. 

Thanks for the update.
