### ISSUE TITLE
Unable to customize the theme - crash

### ISSUE THREAD

**Issue by rohitpal440** [freshdesk/hotline-ios#11]
My Project is working fine without customization of theme.
For customisation I followed https://support.hotline.io/support/solutions/articles/221187-hotline-ios-theming-and-customization-guide
I've added a copy of HLTheme.plist to my project. And renamed it to `HotlineTheme.plist`
In `AppDelegate` I initialised the Hotline with `config?.themeName = "HotlineTheme.plist"`

Now When I run the app, It crashes with following message
` Terminating app due to uncaught exception 'HOTLINE_SDK_INVALID_THEME_FILE', reason: 'You are attempting to set a theme file "HotlineTheme.plist" that is not linked with the project through HLResourcesBundle'`

**Comment by arvpo** [comment]
Hi Rohit,

Please remove the extension .plist when you are setting the theme name, it should work.
Do give this a try and let me know if the issue still persists.

**Comment by rohitpal440** [comment]
Thanks,
It worked.
