### ISSUE TITLE
Is there any method to fetch previous conversation with external ID?

### ISSUE THREAD

**Issue by rohitpal440** [freshdesk/hotline-ios#12]
Hi There,
I'm using Hotline in my iOS app. When an user logout, we clear user data.
Is there any method if same user log in and we populate its previous conversation.

And user's conversation should sync across multiple devices.

**Comment by siddharth-gopalasundaram** [comment]
Hey Rohit,
We do not have a mechanism in place to restore a users conversation. Generally we have noticed that users rarely log out of their mobile app unlike in a web browser as this is a personal device.
One suggested way to handle logout /login in the event if this happening is to clear user data only after checking if the new login is different from the previous login. 
Also we treat each device as a unique install so the conversations cannot be synched across devices. I am extremely sorry for not being able to help with this.

That said, I understand that every app may need a different implementation, so in case the above work around is not enough to help you out, please feel free to mail support@hotline.io with more details about your requirement.

Thanks,
Sid
