### ISSUE TITLE
how to change the title and button text of Navigation Bar to Uppercase.

### ISSUE THREAD

**Issue by rohitpal440** [freshdesk/hotline-ios#17]
Hi team,
I was wondering if there is any way to convert texts in navigation bar such as Title and Buttons text to uppercase. Since in our app we follow this convention of using upper case in Nav bar.

**Comment by hrishikesh-p** [comment]
Here are a couple of things you can do to achieve this.  

1) Use upper case string values in Localizable.strings file.  check "String customizations" section on [this article](https://support.hotline.io/support/solutions/articles/221185-hotline-ios-sdk-integration)
2) Define your channel  names and Category names in Caps on the portal. 

This should allow you to achieve the result you want. 

We currently do not have a way to enforce uppercase on title by default. We will look into it .
