### ISSUE TITLE
Where do you guys store chat data on device?

### ISSUE THREAD

**Issue by rohitpal440** [freshdesk/hotline-ios#18]
hi team, 
I would like to know where are you storing chat data on device? I'm seeing some unexpected behaviour.

**Comment by hrishikesh-p** [comment]
Hey Rohit ( @rohitpal440 )  , 

We use core data to store and forward chat data on the mobile device. The core data file should be part of the app's library folder. Can you please explain the unexpected behaviour you are noticing ?

**Comment by rohitpal440** [comment]
hi @hrishikesh-p ,
I'm getting the chat history even after reinstall.

How to reproduce
1. Fresh install an app using hotline as chat support from app store and Login into the app as USER A.
2. chat with agent.
3. Now uninstall the app.
4. Do fresh installation from app store and login into app as USER B.
5. open hotline
6. you will see the previous chat of User A as User B.

I've seen this behavior in our app and other apps like zomato.

**Comment by rohitpal440** [comment]
hi @hrishikesh-p ,
It would be great to know any update on above issue.

**Comment by hrishikesh-p** [comment]
Hey Rohit @rohitpal440 

The SDK is designed to restore the user's conversation assuming that multiple users will not be using the same app on the same phone. 

If the user logs out of the app , then you can use the [clearUserData](https://github.com/freshdesk/hotline-ios/blob/master/HotlineSDK/Hotline.h#L172-L180) API to clean up the chat history for the user. But this does not address the scenario where user uninstalls without logging out. 

You can detect a new install on the app, You can call clearUserData if the app being launched for the first time to clear up userInfo. This will address the scenario you mentioned.

**Comment by hrishikesh-p** [comment]
@rohitpal440  Also , this restore feature wont work on iOS 10.3 ( and higher)  unless you have enabled Keychain Sharing.  

[Reference](https://forums.developer.apple.com/thread/72271)
