### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kaushaldream11** [freshdesk/hotline-ios#2]
I am getting this crash in Hotline sdk.

Terminating app due to uncaught exception 'NSGenericException', reason: '**\* Collection <__NSCFSet: 0x7aea03e0> was mutated while being enumerated.'
**\* First throw call stack:
(
0 CoreFoundation 0x01d82a14 __exceptionPreprocess + 180
1 libobjc.A.dylib 0x0497fe02 objc_exception_throw + 50
2 CoreFoundation 0x01d822b6 __NSFastEnumerationMutationHandler + 166
3 CoreData 0x018a0a2e -[NSManagedObjectContext executeFetchRequest:error:] + 3758
4 Dream11 0x004c0e00 +[KonotorCustomProperty getUnuploadedProperties] + 237
5 Dream11 0x004be45c __44+[HLCoreServices uploadUnuploadedProperties]_block_invoke + 166
6 libdispatch.dylib 0x05b99377 _dispatch_call_block_and_release + 15
7 libdispatch.dylib 0x05bbc9cd _dispatch_client_callout + 14
8 libdispatch.dylib 0x05ba2985 _dispatch_root_queue_drain + 1008
9 libdispatch.dylib 0x05ba258e _dispatch_worker_thread3 + 115
10 libsystem_pthread.dylib 0x05efc270 _pthread_wqthread + 1050
11 libsystem_pthread.dylib 0x05ef9f82 start_wqthread + 34
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by hrishikesh-p** [comment]
we are looking into this ..

**Comment by hrishikesh-p** [comment]
https://github.com/freshdesk/hotline-ios/releases/tag/v1.0.3  has this fix . Could you please update and check ?

**Comment by hrishikesh-p** [comment]
closing this issue. Please reopen if you happen to see this again . @kaushaldream11
