### ISSUE TITLE
Wrong height on chat bubbles

### ISSUE THREAD

**Issue by iangmaia** [freshdesk/hotline-ios#22]
We've just upgraded to the latest Hotline SDK and noticed the following issue, that wasn't there before:

![simulator screen shot 28 sep 2017 10 39 53](https://user-images.githubusercontent.com/2152244/30957612-0ae8f440-a43b-11e7-8b40-d2b01ac84cb6.png)

The chat bubbles height sometimes is a bit off: in this screenshot, the first and the last ones.

The previous version of the SDK we were using, 1.3.3, was completely fine.

**Comment by harish-kumarc** [comment]
Hi @iangmaia 
From sdk v1.3.5 we have added a feature to add agent name for agent side messages. 
You can implement it via defining value for ``` "messages_agent_label_text" = "Your support name"; ``` in your SDK localise strings “HLLocalizable.string” file. 
If you do not want to display anything, make sure that the value is empty as ```"messages_agent_label_text"="";```  else it will show blank agent name with padding.
Thanks

**Comment by iangmaia** [comment]
Hi @harish-kumarc, many thanks for the explanation, it is clear now.

**Comment by iangmaia** [comment]
Just tested doing exactly as you described,
`"messages_agent_label_text" = "";`
But the extra padding is still there. Actually, I would expect that, if the key isn't present, the padding shouldn't be there anyways.
I've tried to set the string to different values and nothing was shown as the agent label.

Any other suggestions on fixing it?

**Comment by harish-kumarc** [comment]
Hi @iangmaia ,
Correct if the key isn't present in HLLocalizable.strings then the padding shouldn't be there. 
Can you please confirm that you are on latest iOS SDK v1.3.6
And also check you are following changes in correct all/available localize string file(s)
If it still persists we can probably get on a screen share and sort this out.
Thanks

**Comment by iangmaia** [comment]
We're using 1.3.6 like I mentioned in my first message. We're using Cocoapods.

Now I've done a test removing all the resources we have in the app (localization and theme configuration), leaving only what's in the library. This was the result: the problem is still there.

![simulator screen shot 28 sep 2017 15 51 28](https://user-images.githubusercontent.com/2152244/30970287-06e11bf0-a465-11e7-8151-d5c5c6a65106.png)

**Comment by harish-kumarc** [comment]
Hi @iangmaia 
Sorry, but we are but unable to replicate the issue as you are mentioning. 
For more clearance I have attached a sample app here. Please add your appId and appKey in appdelegate file and can use it as reference. I commented out "messages_agent_label_text" to escape agent name and there won't be any extra-spacing or padding.  
Please check it and let us know if it resolve your problem. If the issue still persist will forward with screenshare session.
Thanks
[SampleHotlineApp.zip](https://github.com/freshdesk/hotline-ios/files/1342578/SampleHotlineApp.zip)

**Comment by iangmaia** [comment]
Hi @harish-kumarc -- your sample worked, but it had a change inside the downloaded Pod commenting out the key (which isn't a good practice).

I've found my way around by having the key == value (so it is effectively the same as removing it) in my local HLLocalizable.strings. Now there's no padding added.
`"messages_agent_label_text"="messages_agent_label_text";`

Thanks,
Ian

**Comment by harish-kumarc** [comment]
Hi @iangmaia 
Great !!
The key in sample is specifically commented out for your understanding only that if the key isn't available then we are not adding any extra padding. And if you remove comment part then value for the key ```"messages_agent_label_text"``` is an Empty String and thats how we are deciding to display agent name.

Thanks
