### ISSUE TITLE
unable to execute command: Segmentation fault: 11

### ISSUE THREAD

**Issue by kunila** [freshdesk/hotline-ios#3]
I can generate a build if i use HotlineSDK (1.0.2). However cannot archive the project when HotlineSDK (1.0.3) is used. I am using Xcode 7.2.1

I get the following error:
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)

**Comment by hrishikesh-p** [comment]
@kunila  The issue is specific to Xcode 7.2.1 . We will have a  fix very soon. 
Meanwhile, it should work fine if you upgrade to Xcode 7.3 .

**Comment by hrishikesh-p** [comment]
We have fixed this .. Can you please update to 1.0.4 ?
