### ISSUE TITLE
Alert about push messages, even if the developer isn't using push

### ISSUE THREAD

**Issue by iangmaia** [freshdesk/hotline-ios#5]
As far as I understand, all the Hotline configuration to receive push messages is optional.

Even so, the SDK automatically shows an Alert mentioning something about push notifications the first time you open a chat screen (which doesn't make sense if we're not using push).

**Comment by hrishikesh-p** [comment]
Although the push notification setup can be skipped. We recommend you to enable push notifications. Push notifications ensures a  real-time messaging experience for the user and gets them back in the app when there is a message from the agent side. 

Push notification setup is optional if you are using the SDK only for FAQs .
