### ISSUE TITLE
Add more customization to the theme file

### ISSUE THREAD

**Issue by NicolasMahe** [freshdesk/hotline-ios#7]
I really would like to customise more the UI, especially in the ConversationsUI.
I would like to set:
- the background color of the table view
- the background color of the User and Agent bubble
- the color of the add picture button (arrow on the left of the message input)

**Comment by arvpo** [comment]
Hey @NicolasMahe,
1. Currently the option for changing conversation UI background is not available, we will add it in the upcoming release.
2. To change the background color of the bubble images and the picture attach button, 
- Please locate images (hotline_bubble_left, hotline_bubble_right, hotline_upload) in the HLResources.bundle
- Change the fill color using any image editor.
- Add it to the main project and update the image name in the HLTheme.plist under images section.

<img width="645" alt="screen shot 2016-10-14 at 7 17 40 pm" src="https://cloud.githubusercontent.com/assets/4346153/19389870/4aaa011a-9243-11e6-8c3d-5956af6be420.png">

**Comment by NicolasMahe** [comment]
Do you have a release date for the upcoming release with the option to change the background ?

**Comment by arvpo** [comment]
Hey @NicolasMahe,
We will roll out an update next week.
