### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by sraj** [freshdesk/hotline-ios#9]
Update Podspec to add Security.framework, FDKeyChainStore requires it. I'm not sure why no one had this issue before. Am i missing something?

**Comment by arvpo** [comment]
Hi Suman,

Sorry for the late reply, we have checked it from our end, we are not seeing the issue that you have mentioned. If it is stopping you from using the SDK please add that dependency in your **Linked framework and Libraries** section as a workaround for now. We will investigate this further and find out if any of our customer is facing this issue., If required we will add that dependency to our podspec and do update you on that. Please do reach out if you have any issue.

Thanks.
